[package]
name = "gol-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "0.55.0"
piston2d-glium_graphics = "0.95.0"
piston2d-graphics = "0.44.0"
pistoncore-glutin_window = "0.72.0"